---

- name: Configuration - setup interfaces name by mac address
  template:
    src: "templates/etc/udev/rules.d/model_persistent_net.j2"
    dest: "/etc/udev/rules.d/60_{{ item.interface }}_persistent_net.rules"
    owner: root
    group: root
    mode: "0644"
  loop:
    - mac: "{{ mac_eth0 }}"
      interface: "eth0"
      interface_reg: "eth*"
    - mac: "{{ mac_eth1 }}"
      interface: "eth1"
      interface_reg: "eth*"
    - mac: "{{ mac_wlan0 }}"
      interface: "wlan0"
      interface_reg: "wlan*"
    - mac: "{{ mac_wlan1 }}"
      interface: "wlan1"
      interface_reg: "wlan*"
    - mac: "{{ mac_wlan2 }}"
      interface: "wlan2"
      interface_reg: "wlan*"
  tags:
    - config-set-interface-names

- name: Configuration - network interfaces
  template:
    src: "templates/etc/network/interfaces.d/{{ item.model }}.j2"
    dest: "/etc/network/interfaces.d/{{ item.interface }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop:
    - interface: eth0
      model: 'model_static_ip'
      address: '192.168.{{ eth0_subnet }}.{{ fin_ip_eth0 }}'
      netmask: '255.255.255.0'
      gateway: '192.168.{{ eth0_subnet }}.{{ fin_ip_eth0 }}'
      dns1: '4.4.4.4'
      dns2: '8.8.8.8'
    - interface: eth1
      model: 'model_hotplug_iphone'
    - interface: wlan0
      model: 'model_disable'
    - interface: wlan1
      model: 'model_static_ip'
      address: '192.168.{{ wlan1_subnet }}.{{ fin_ip_wlan1 }}'
      netmask: '255.255.255.0'
      gateway: '192.168.{{ wlan1_subnet }}.{{ fin_ip_wlan1 }}'
      dns1: '4.4.4.4'
      dns2: '8.8.8.8'
    - interface: wlan2
      model: 'model_static_ip'
      address: '192.168.{{ wlan2_subnet }}.{{ fin_ip_wlan2 }}'
      netmask: '255.255.255.0'
      gateway: '192.168.{{ wlan2_subnet }}.{{ fin_ip_wlan2 }}'
      dns1: '4.4.4.4'
      dns2: '8.8.8.8'
  tags:
    - config-interface

- name: Configuration - create conf dirs
  ansible.builtin.file:
    path: /etc/netdata
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - config-create-dirs

- name: Configuration - Copying configs files
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "/etc/netdata/netdata.conf"
    - "/etc/nas_cifs_creds"
    - "/etc/dhcpcd.conf"
    - "/etc/hosts"
    - "/etc/iptables/rules.v4"
  tags:
    - config-copy

- name: Configuration - dnsmasq config
  template:
    src: "templates/etc/dnsmasq.d/model_pre_filled.j2"
    dest: "/etc/dnsmasq.d/{{ item.interface }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop:
    - interface: eth0
      subnet: '{{ eth0_subnet }}'
    - interface: wlan1
      subnet: '{{ wlan1_subnet }}'
    - interface: wlan2
      subnet: '{{ wlan2_subnet }}'
  tags:
    - config-dnsmasq

- name: Configuration - hostapd config
  template:
    src: "templates/etc/hostapd/{{ item.interface }}.j2"
    dest: "/etc/hostapd/{{ item.interface }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop:
    - interface: wlan1
    - interface: wlan2
  tags:
    - config-hostapd

# Set ip forwarding on in /proc and verify token value with the sysctl command
- name: Configuration - Enable ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
  tags:
    - config-forward

- name: Configuration - Add nas in mounts
  ansible.posix.mount:
    src: //192.168.2.100/Volume_1
    path: /mnt/nas
    fstype: cifs
    opts: credentials=/etc/nas_cifs_creds,dir_mode=0755,file_mode=0755,uid=1000,gid=1000,vers=1.0,auto
    state: present
  tags:
    - config-fstab
