---

- name: Gestion du réseau / wifi - pre-connect
  import_tasks: pre-connect.yml
  tags:
    - network-pre-connect

- name: Installation
  import_tasks: install.yml
  tags:
    - install

- name: Configuration
  import_tasks: config.yml
  tags:
    - config

- name: Configuration - Source wifi
  import_tasks: config_src_wifi.yml
  tags:
    - config-srcwifi
