---

- name: Gestion du reseau - setup interfaces name by mac address
  template:
    src: "templates/etc/udev/rules.d/model_persistent_net.j2"
    dest: "/etc/udev/rules.d/60_{{ item.interface }}_persistent_net.rules"
    owner: root
    group: root
    mode: "0644"
  loop:
    - mac: "{{ mac_eth0 }}"
      interface: "eth0"
      interface_reg: "eth*"
    - mac: "{{ mac_wlan0 }}"
      interface: "wlan0"
      interface_reg: "wlan*"
  tags:
    - config-set-interface-names

- name: Gestion du reseau - pre-connect - setup interfaces ip config
  template:
    src: "templates/etc/network/interfaces.d/{{ item.model }}.j2"
    dest: "/etc/network/interfaces.d/{{ item.interface }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - interface: eth0
      model: "model_static_ip"
      address: "192.168.2.1"
      gateway: "192.168.2.1"
      netmask: "255.255.255.0"
      dns1: "4.4.4.4"
      dns2: "8.8.8.8"
    - interface: wlan0
      model: "model_empty"
  tags:
    - network-pre-connect-interface

- name: Gestion du wifi - pre-connect - wpa_supplicant wifi connection
  template:
    src: "templates/etc/wpa_supplicant/wpa_supplicant.conf.j2"
    dest: "/etc/wpa_supplicant/wpa_supplicant.conf"
    owner: root
    group: root
    mode: "0644"
  tags:
    - network-pre-connect-wpa-supplicant-file

- name: Gestion du wifi - pre-connect - dhcpcd conf (basic)
  template:
    src: "templates/etc/dhcpcd.conf.j2"
    dest: "/etc/dhcpcd.conf"
    owner: root
    group: root
    mode: "0644"
  tags:
    - network-pre-connect-dhcpcd-file

# sudo rfkill unblock wifi
- name: Gestion du reseau + wifi - pre-connect - rfkill
  become: yes
  command: rfkill unblock wifi
  tags:
    - network-pre-connect-service-maj

# sudo ifconfig wlan0 up
- name: Gestion du reseau + wifi - pre-connect - ifconfig up
  become: yes
  command: ifconfig wlan0 up
  tags:
    - network-pre-connect-service-maj

- name: Gestion du wifi - pre-connect - reboot
  reboot:
  tags:
    - network-pre-connect-reboot
